### ISSUE TITLE
Uploads randomly failing with SSLEOFError

### ISSUE THREAD

**Issue by QuLogic** [scientific-python/upload-nightly-action#22] opened 2023-07-15 16:31 UTC
In Matplotlib, the actions are sporadically, but rather often, failing somewhere in the middle of the upload.

For example, [from this most recent job](https://github.com/matplotlib/matplotlib/actions/runs/5559847339/jobs/10156354531):
```
Processing 'dist/matplotlib-3.8.0.dev1520+g5846838ac4-pp39-pypy39_pp73-macosx_10_12_x86_64.whl'
Detecting file type...
File type is "Standard Python"
Extracting standard python attributes for upload
Creating package "matplotlib"
Creating release "3.8.0.dev1520+g5846838ac4"
Uploading file "scientific-python-nightly-wheels/matplotlib/3.8.0.dev1520+g5846838ac4/matplotlib-3.8.0.dev1520+g5846838ac4-pp39-pypy39_pp73-macosx_10_12_x86_64.whl"

  0%|          | 0.00/7.18M [00:00<?, ?B/s]
  0%|          | 8.00k/7.18M [00:00<03:27, 36.3kB/s]
  1%|          | 88.0k/7.18M [00:00<00:25, 292kB/s] 
  4%|▍         | 328k/7.18M [00:00<00:09, 761kB/s] 
Error:  HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2396)')))
```

The [previous job also failed](https://github.com/matplotlib/matplotlib/actions/runs/5549689906/jobs/10149076853)
```
Processing 'dist/matplotlib-3.8.0.dev1514+g6391678cc1-pp39-pypy39_pp73-win_amd64.whl'
Detecting file type...
File type is "Standard Python"
Extracting standard python attributes for upload
Creating package "matplotlib"
Creating release "3.8.0.dev1514+g6391678cc1"
Uploading file "scientific-python-nightly-wheels/matplotlib/3.8.0.dev1514+g6391678cc1/matplotlib-3.8.0.dev1514+g6391678cc1-pp39-pypy39_pp73-win_amd64.whl"

  0%|          | 0.00/7.27M [00:00<?, ?B/s]
  0%|          | 8.00k/7.27M [00:00<02:56, 43.2kB/s]
  2%|▏         | 160k/7.27M [00:00<00:18, 399kB/s]  
Error:  HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2396)')))
```

The 3 before that worked fine.

**Comment by matthewfeickert** [comment] 2023-07-15 17:05
Thanks for reporting this @QuLogic. As we discussed my guess is that this is an S3 problem that we'll need to talk to Anaconda Cloud about, but after PR #23 is in I'd like to see if that has any effect (it shouldn't! but I want to empirically check.).

**Comment by matthewfeickert** [comment] 2023-07-16 15:27
This seems to be something that happens with `anaconda-client` in the past (c.f. https://github.com/Anaconda-Platform/anaconda-client/issues/81) so I'm going to escalate this there.

**Comment by matthewfeickert** [comment] 2023-07-16 15:32
This is now https://github.com/Anaconda-Platform/anaconda-client/issues/675.

**Comment by matthewfeickert** [comment] 2023-07-21 03:34
@QuLogic @ksunden as it seems that there haven't been recent upload failures (for this week at all) how do you feel about closing this Issue and just having all follow up happen in https://github.com/Anaconda-Platform/anaconda-client/issues/675? Or would you prefer that there be provenance of open Issues till this gets resolved?

**Comment by matthewfeickert** [comment] 2024-01-24 20:41
@QuLogic @ksunden as it doesn't seem like this has happened for a long time, and so the problem is resolved on Anaconda Cloud's side, are you okay with me closing this?

**Comment by matthewfeickert** [comment] 2024-02-08 17:07
I'm going to close this as it seems that this got fixed on the Anaconda Cloud side of things.

**Closed by matthewfeickert** 2024-02-08 17:07 UTC
